# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        uploads:
            uri_prefix: /uploads/files
            upload_destination: '%kernel.project_dir%/public/uploads/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
