version: '3.9'

services:
    postgres:
        image: postgres:16
        container_name: postgres_ueh_final
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: ueh_final
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data:
