# Dockerfile.nginx
FROM nginx:alpine

# Xóa config mặc định của Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copy file config Nginx của bạn vào container
# File này sẽ được chỉnh sửa ở bước 3
COPY ./docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf