# Dockerfile.nginx

FROM nginx:alpine

# Xoá file cấu hình mặc định
RUN rm /etc/nginx/conf.d/default.conf

# Chép file cấu hình DÀNH RIÊNG CHO RENDER vào image
COPY ./docker/nginx/conf.d/render.conf /etc/nginx/conf.d/default.conf