version: "3.8"

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./api:/var/www/html
    environment:
      - APP_ENV=prod

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./api:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php

volumes:
  db_data:
  caddy_data:
  caddy_config:
