services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: symfony_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ueh_final
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ueh_final"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  symfony_network:
    driver: bridge 